### ISSUE TITLE
Allow specifying used constructor with annotation

### ISSUE THREAD

**Issue by komu** [EvidentSolutions/dalesbred#19]
Support using annotation to specify which constructor Dalesbred should use for instantiation. If annotation is present on one constructor, the normal constructor resolution logic would be skipped. Even private constructors could be used because the annotation would make it explicit that its the programmers intent to use that.

**Comment by groie** [comment]
This issue is being worked on in the [constructor-annotation-branch](https://github.com/EvidentSolutions/dalesbred/tree/constructor-annotation).
