### ISSUE TITLE
IN clause & Stored Procedures Call Support 

### ISSUE THREAD

**Issue by HussDev** [EvidentSolutions/dalesbred#34]
Hi

is there any special support for SQL IN clause 
and also for calling stored procedures and getting out param ?

Thanks

**Comment by komu** [comment]
Hi,

For SQL IN clauses I generally try to keep the query constant and pass an array to database. For example, using PostgreSQL the following would work:

```java
List<Integer> ids = ...
SqlArray idArray = SqlArray.of("int", ids); // "int" here is database specific type name
List<Foo> foos = db.findAll(Foo.class, "select bar, baz from foo where id = any(?)", array);
```

Unfortunately not all databases support passing arrays easily, so you need to create the query manually in that case. [QueryBuilder.appendPlaceholders](http://dalesbred.org/docs/api/org/dalesbred/query/QueryBuilder.html#appendPlaceholders-java.util.Collection-) is helpful in those cases:

```java
SqlQuery q = new QueryBuilder("select bar baz from foo where id in ")
        .appendPlaceholders(ids)
        .build();
```

With `QueryBuilder`, you lose static the static analysis provided by IDEA though. ☹️ 

There's no support for calling stored procedures. I've had very little need for that myself, so I've never gotten around to implementing that. Of course you can execute a transaction callback and then do whatever you wish against the connection, but that's as far as Dalesbred supports you. But anyway that's a good idea for future development.

**Comment by komu** [comment]
I added #35 for tracking stored procedure support, but I have no immediately plans on starting working on it. Design ideas, prototypes or pull requests would be appreciated.
