### ISSUE TITLE
Update reference documentation for 1.0

### ISSUE THREAD

**Issue by komu** [EvidentSolutions/dalesbred#4]
Write all examples in Java 8, cover the new functionality.

**Comment by plandem** [comment]
how safe is to use v1.0? api changes in future? i would like to use at production.

**Comment by komu** [comment]
It should be relatively safe: there could still be a some API changes in less commonly used features (e.g. custom Dialect, Instantiators, TypeConversions etc.), but the core functionality should remain stable. Anyway, I will document all the changes in changelog so if there are some changes, there should be a clear migration path.

All in all, I think 1.0 is more or less ready to be released, but I still want to take my time and make sure that I've polished everything that I want to, because after 1.0 I won't make any breaking changes. So if you want to make absolutely sure you don't have to rewrite a single line of code, then you'll have to wait for 1.0, but if you can consider possibly having to make few changes when upgrading, then the current versions should be ok.

In our company we have probably around 15 projects using Dalesbred and we wish to upgrade them to 1.0 at some point, so I will try to keep the migration path as clear as possible for that reason as well.

**Comment by plandem** [comment]
i see. then i will stick with 1.0a
