### ISSUE TITLE
How build  parameterized query with subquery? 

### ISSUE THREAD

**Issue by voronovmaksim** [EvidentSolutions/dalesbred#48]
I would like to execute query like that:
select * from cats where cat_id in (select ids from unnest(cast('{1}' as arraynumbers)) as ids

arraynumbers is my type(Domain in postgres)

I make next query in my code:

```
String query = "select * from cats where cat_id in (:ids)"
String subquery = "select ids from unnest(cast('{1}' as arraynumbers) as ids
```

and then code:
```
Map parameters = new HashMap<>();
parameters.put("ids", subquery)
SqlQuery sqlQuery = namedQuery(query, parameters);
db.findAll(Cat.class ,sqlQuery)
```

i get exception like that:
ERROR: operator does not exist: bigint = character varying 

And there is way to get access  to statement in order to use method setObject() ?https://docs.oracle.com/javase/7/docs/api/java/sql/PreparedStatement.html#setObject(int,%20java.lang.Object)

**Comment by komu** [comment]
Hi,

First of all, it seems like you are creating a query where the string of the subquery is passed as an argument. So in effect you get the same as if you'd written:

```sql
select * from cats where cat_id in ('select ids from unnest(cast('{1}' as arraynumbers) as ids')
```

So now the error message makes sense. You're comparing `cat_id` (bigint) agains the string `"select ids from unnest(cast('{1}' as arraynumbers) as ids"`. Obviously this wouldn't work even with a raw JDBC: SQL does not allow passing parts of the query dynamically, only the values referenced by the query. So if you need to construct the query from parts, you need to say something like:

```java
String subquery = "select ids from unnest(cast('{1}' as arraynumbers) as ids";
String query = "select * from cats where cat_id in (" + subQuery + ")";
```

After this Dalesbred just passes the query to database and it's up to the database to do the rest.

It's possible to customize how Dalesbred does the data binding for various types so you could convert your own classes to `PGobject` which can then represent the custom domains in PostgreSQL. But in this case, it's not even necessary.
